config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root "items#index"
  resources :items
  resources :carts
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  resources :cart_items
  resources :charges, only: [:new, :create]
  
  namespace :admin do
  	resources :items
    resources :users
    resources :carts
  	root 'admin#index'
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user

	validates :first_name, presence:true
	validates :last_name, presence:true
	validates :street, presence:true 
	validates :city, presence:true
	validates :zip_code,
		presence:true,
		format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[abAB]))[0-9]{3}\z/, message: "Le code postal est invalide" }

	validates :phone_number, 
		presence:true,
		format: { with: /\A(?:(?:\+|00)33[\s.-]{0,3}(?:\(0\)[\s.-]{0,3})?|0)[1-9](?:(?:[\s.-]?\d{2}){4}|\d{2}(?:[\s.-]?\d{3}){2})\z/, message: "Entrez un numéro français, s'il vous plait !" }

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :authenticate_user!
before_action :verify_profile, only: [:show, :edit]
before_action :verify_user_rights, only: [:show, :edit]

  def new
  	@profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    @current_cart = current_user.carts.where("status = 0")[0]


    if @profile.save
       flash[:notice] = "Vous avez bien créé votre profil"
       redirect_to cart_path(@current_cart.id)
     else
      if @profile.errors.any?
        @profile.errors.full_messages.each do |message|
          flash[:error] =  "#{message}"
        end
      end
      redirect_to cart_path(@current_cart.id)
    end

  end

  def edit
  	@user = current_user
    @profile = Profile.find_by(user_id: @user.id)
  end

  def update
  	@user = current_user
    @profile = Profile.find_by(user_id: @user.id)
    @current_cart = @user.carts.where("status = 0")[0]
    puts "**"*100
    puts @current_page
    puts @params
    puts "**"*100
  	post_params = params[:profile]
    if @profile.update(first_name: post_params[:first_name], last_name: post_params[:last_name], street: post_params[:street], city: post_params[:city], zip_code: post_params[:zip_code], phone_number: post_params[:phone_number])
      flash[:notice] = "Vous avez bien mis à jour votre profil"

      redirect_to request.referrer

    else
      if @profile.errors.any?
        @profile.errors.full_messages.each do |message|
          flash[:error] =  "#{message}"
        end
      end
      redirect_to request.referrer
    end
  end

  def show
    @user = current_user
    @profile = Profile.find(@user.profile.id)
    @cart_all = current_user.carts.where(status: 1)
    @cart = Cart.find_by(user_id: current_user.id, status: 1)
  end

  private

  def profile_params
  	params.permit(:first_name, :last_name, :street, :city, :zip_code, :phone_number)
  end

  def verify_profile
   unless current_user.profile != nil
   flash[:error] = "Vous n'avez pas de profil"
   redirect_to root_path
  end
end

  def verify_user_rights
    @profile_page = Profile.find(params[:id])
    @profile_user = current_user.profile
    unless @profile_user.id == @profile_page.id
    flash[:error] = "Vous n'avez pas les droits"
    redirect_to root_path
    end
  end



end

app/helpers/profiles_helper.rb
module ProfilesHelper

	def current_user_profile?
    current_user.profile != nil
	end

  def order_amount(id)
    subtotal = 0
    id.cart_items.each do |cart_item|
      price = cart_item.item.price * cart_item.quantity
      subtotal += price
    end
    return subtotal
  end

end

app/views/profiles/_edit_form.html.erb
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>

        <%= form_for @profile do |f| %>
          <h1 class="h3 mb-3 font-weight-normal text-center">Mes Informations</h1>
          <h2 class="h5 mb-3 font-weight-normal text-left">Mes Informations</h2>
          <div class="form-group">
            <%= f.text_field :first_name, class: 'form-control', placeholder: 'Prénom'%></br>
            <%= f.text_field :last_name, class: 'form-control', placeholder: 'Nom'%></br>
            <%= f.text_field :phone_number, class: 'form-control', placeholder: 'Numéro de téléphone'%></br>
          </div>
          <h2 class="h5 mb-3 font-weight-normal text-left">Mon adresse de facturation</h2>
          <div class="form-group">
            <%= f.text_field :street, class: 'form-control', placeholder: 'Rue'%></br>
            <%= f.text_field :city, class: 'form-control', placeholder: 'Ville'%></br>
            <%= f.text_field :zip_code, class: 'form-control', placeholder: 'Code Postal'%></br>
          <small class="text-gray">* Champs obligatoires</small>
          </div>
          <div class="form-actions mt-3">
            <button type="submit" class="btn btn-secondary"> Mettre à jour </button>
            <%= link_to "Payer ma commande", new_charge_path, class:"btn btn-primary" %>
          </div>
        <% end %>
    </div>
  </div>

app/views/profiles/_new_form.html.erb
  <div class="row">
    <div class="col-md-8 offset-md-2">

        <%= form_tag({controller: "profiles", action: "create"}, method: "post") do %>
          <h1 class="h3 mb-3 font-weight-normal text-center">Mes Informations</h1>
          <h2 class="h5 mb-3 font-weight-normal text-left">Mes Informations</h2>
          <div class="form-group">
            <%= text_field_tag 'first_name', '', class: 'form-control', placeholder: 'Prénom *'%>
            <%= text_field_tag 'last_name', '', class: 'form-control', placeholder: 'Nom *'%>
            <%= text_field_tag 'phone_number', '', class: 'form-control', placeholder: 'Numéro de téléphone *'%>
          </div>
          <h2 class="h5 mb-3 font-weight-normal text-left">Mon adresse de facturation</h2>
          <div class="form-group">
            <%= text_field_tag 'street', '', class: 'form-control', placeholder: 'Rue *'%>
            <%= text_field_tag 'city', '', class: 'form-control', placeholder: 'Ville *'%>
            <%= text_field_tag 'zip_code', '', class: 'form-control', placeholder: 'Code Postal *'%>
            <small class="text-gray">* Champs obligatoires</small>
          </div>
          <div class="form-actions mt-3">
            <%= submit_tag "Enregistrer", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>

app/views/profiles/edit.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
        <%= form_for @profile do |f| %>
          <h1 class="h3 mb-3 font-weight-normal text-center">Mes Informations</h1>
          <h2 class="h5 mb-3 font-weight-normal text-left">Mes Informations</h2>
          <div class="form-group">
            <%= f.text_field :first_name, class: 'form-control', placeholder: 'Prénom'%></br>
            <%= f.text_field :last_name, class: 'form-control', placeholder: 'Nom'%></br>
            <%= f.text_field :phone_number, class: 'form-control', placeholder: 'Numéro de téléphone'%></br>
          </div>
          <h2 class="h5 mb-3 font-weight-normal text-left">Mon adresse de facturation</h2>
          <div class="form-group">
            <%= f.text_field :street, class: 'form-control', placeholder: 'Rue'%></br>
            <%= f.text_field :city, class: 'form-control', placeholder: 'Ville'%></br>
            <%= f.text_field :zip_code, class: 'form-control', placeholder: 'Code Postal'%></br>
          <small class="text-gray">* Champs obligatoires</small>
          </div>

          <div class="form-actions mt-3">
            <button type="submit" class="btn btn-secondary mr-3"> Mettre à jour </button>
            <%= link_to "Retour au profil", profile_path(@profile.id), class: "btn btn-secondary"%>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>

      <% if @profile.errors.any? %>
  <p>Registration failure. Please checkout the following points :</p>
  <ul>
    <% @profile.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
				<%= form_tag url_for(action: 'create'), method: "post" do %>
				  <h1 class="h3 mb-3 font-weight-normal text-center">Mes Informations</h1>
          <h2 class="h5 mb-3 font-weight-normal text-left">Mes Informations</h2>
          <div class="form-group">
					  <%= text_field_tag 'first_name', '', class: 'form-control', placeholder: 'Prénom *'%>
					  <%= text_field_tag 'last_name', '', class: 'form-control', placeholder: 'Nom *'%>
					  <%= text_field_tag 'phone_number', '', class: 'form-control', placeholder: 'Numéro de téléphone *'%>
					</div>
					<h2 class="h5 mb-3 font-weight-normal text-left">Mon adresse de facturation</h2>
					<div class="form-group">
					  <%= text_field_tag 'street', '', class: 'form-control', placeholder: 'Rue *'%>
					  <%= text_field_tag 'city', '', class: 'form-control', placeholder: 'Ville *'%>
					  <%= text_field_tag 'zip_code', '', class: 'form-control', placeholder: 'Code Postal *'%>
					  <small class="text-gray">* Champs obligatoires</small> 
					</div>
					<div class="form-actions mt-3">  
					  <%= submit_tag "Enregistrer", class: "btn btn-secondary" %>
					</div>  		
				<% end %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div id="small-banner" class="page-title d-flex" aria-label="Page title">
      <div class="container text-left align-self-center">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                  <li class="breadcrumb-item"><%= link_to "Accueil", root_path %></li>
                  <li class="breadcrumb-item"><%= link_to "Profil", root_path %></li>
              </ol>
          </nav>
          <h1 class="page-title-heading"> Mon espace Profil </h1>
      </div>
</div>


<!-- Contacts Card Default -->
<div class="container">
    <div class="row">
        <div class="card col-6">
            <div class="card-body">
  	             <div class="author-card pb-3">
                     <div class="author-card-cover"></div>
                         <div class="author-card-profile mt-30" >
	                           <div class="author-card-details">
	                                <h5 class="author-card-name text-lg">
                                  <h6><%= @profile.first_name %> <%= @profile.last_name %></h6></h5>
                                  <span class="author-card-position"><%= current_user.created_at %></span>
	                           </div>
                             <div class="widget widget-contacts">
                  				      <ul>
                    				        <li>
                                        <i class="fas fa-home"></i>
                                        <span> Adresse </span>
                      				          <a><%= @profile.street %>,<%= @profile.zip_code %>,<%= @profile.city %></a>
                    				        </li>
                    				        <li>
                      				          <i class="fas fa-at"></i>
                      				          <span> Email </span>
                      				          <a><%= @profile.user.email %></a>
                    				        </li>
                    				        <li>
                      				          <i class="fas fa-phone"></i>
                      				          <span> Téléphone </span>
                      				          <a><%= @profile.phone_number %></a>
                    				        </li>
                  				      </ul>
                				    </div>
                         </div>
                    </div>
              </div>
              


<!-- Buttons -->
          <p>
            	<%= link_to edit_user_registration_path, class: "btn btn-style-4 btn-secondary btn-sm" do%>
                  <span><i class="fas fa-key"></i> Editer email et/ou mot de passe </span>
               <% end %>

              <%= link_to edit_profile_path(current_user.profile.id), class: "btn btn-style-4 btn-secondary btn-sm" do%>

              <span><i class="fas fa-user-edit"></i> Editer les informations du profil </span>
               <% end %>
          </p>
      </div>


<!-- Orders Table-->
        <div class="card col-6 ">
            <table class="table table-hover mb-0">
              <thead>
                <tr>
                  <th>Commande #</th>
                  <th>Date d'achat</th>
                  <th>Statut</th>
                  <th>Total</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                <% @cart_all.each_with_index do |order, i| %>

                  <td><a class="navi-link" data-toggle="modal"><%=order.id %></a></td>
                  <td><%=order.created_at %></td>
                  <td><span class="badge badge-success m-0"><%=order.status %></span>
                  <td><%= order_amount(order) + (number_of_items(order)*2)  %>€</td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
    </div>
</div>