config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root "items#index"
  resources :items
  resources :carts
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  resources :cart_items
  resources :charges, only: [:new, :create]
  
  namespace :admin do
  	resources :items
    resources :users
    resources :carts
  	root 'admin#index'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	enum status: { in_progress:0, paid:1 }

	has_many :cart_items
	belongs_to :user


end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
	has_many :card_items
  validates :image_url, :title, :description, :price, presence: { message: "Merci de remplir tous les champs obligatoires!" };
  validates :price, numericality: { greater_than: 0,  message: "Le prix doit être supérieur à 0" };
  validates :description, length: { minimum: 20, message: "La description doit faire au minimum 20 caractères" };
  has_one_attached :item_picture # active storage


 def to_param
    [id, title.parameterize, 'en solde sur notre boutique trois petits chats'.parameterize].join("-")
  end


end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user

	validates :first_name, presence:true
	validates :last_name, presence:true
	validates :street, presence:true 
	validates :city, presence:true
	validates :zip_code,
		presence:true,
		format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[abAB]))[0-9]{3}\z/, message: "Le code postal est invalide" }

	validates :phone_number, 
		presence:true,
		format: { with: /\A(?:(?:\+|00)33[\s.-]{0,3}(?:\(0\)[\s.-]{0,3})?|0)[1-9](?:(?:[\s.-]?\d{2}){4}|\d{2}(?:[\s.-]?\d{3}){2})\z/, message: "Entrez un numéro français, s'il vous plait !" }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :welcome_send
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 	has_one :profile


 	has_many :carts

  def welcome_send
  	UserMailer.welcome_email(self).deliver_now
  end


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :require_admin

	def require_admin
	  unless current_user.try(:is_admin?)
	  flash[:error] = "Accès non autorisé"
	  redirect_to root_path
	  end
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

	def require_admin
	  unless current_user.try(:is_admin?)
	  flash[:error] = "Accès non autorisé"
	  redirect_to root_path
	  end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_user_has_a_cart, only: [:show, :edit]
  before_action :verify_cart_status, only: [:show, :edit]
  before_action :verify_user_rights, only: [:show, :edit]
  
  def index
    @cart = Cart.all
  end

  def show
  	@cart = Cart.find(params[:id])
  	@cart_items = @cart.cart_items.order(:id)
    @profile = current_user.profile

	  @subtotal=0
	  @cart_items.each do |cart_item|
		  price = cart_item.item.price 
		  @subtotal+=price
		end
	end

  def create
  	cart = Cart.create(status: 0, user: current_user)
  end

  def update
  	cart = Cart.update(status: 0, user: current_user)
  end


private 

def verify_user_has_a_cart
	#Si l'utilisateur n'as pas de panier 
	unless current_user.carts != nil
    flash[:error] = "Ma biche, crée ton panier plutôt que de t'intéresser à ceux des autres"
    redirect_to root_path
    end
end


def verify_cart_status
	#Si le statut du panier visité est 'paid'
	cart_status = Cart.find(params[:id]).status
	cart_id = params[:id]
	if cart_status == "paid"
    flash[:error] = "Ce panier n'existe plus. Rendez-vous dans votre page profile pour accéder à vos commandes passées"
    redirect_to root_path
	end
end


def verify_user_rights
	#si le panier n'est pas celui de l'utilisateur
   url_id = params[:id].to_i
   cart_id = current_user.carts.find_by("status = 0").id
   unless url_id == cart_id
    flash[:error] = "Ce n'est pas bien de vouloir accéder à un panier qui ne vous appartient pas"
    redirect_to root_path
   end

end



end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

before_action :authenticate_user!
after_action :confirmation_send, only: [:create]
after_action :new_order_send, only: [:create]

	def new
			@cart = current_cart
	end


	def create
		@cart = current_cart
		@amount = (total_cart * 100).round
		@profile_current_user = current_user.profile

		  customer = Stripe::Customer.create({
		    email: params[:stripeEmail],
		    source: params[:stripeToken],
		  })

		  charge = Stripe::Charge.create({
		    customer: customer.id,
		    amount: @amount,
		    description: 'Rails Stripe customer',
		    currency: 'eur',
		  })

	  @cart.update(stripe_customer_id: charge[:customer], status: 1)
	  flash[:notice] = "Your order is complete"
	  redirect_to profile_path(@profile_current_user.id)

		rescue Stripe::CardError => e
		  flash[:error] = e.message
		  redirect_to new_charge_path
		end

		def confirmation_send
			@items = current_user.carts.last.cart_items
      UserMailer.confirmation_email(current_user, @items).deliver_now
    end

		def new_order_send
			@cart_items = current_user.carts.last.cart_items
      AdminMailer.new_order_email(current_user, @cart_items).deliver_now
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :cart_verification, only: [:index]


  def index
    @items = Item.all.order(:id).reverse
  end

  def show
  @item = Item.find(params[:id].to_i)
  @item.increment!(:view)
  @best_items = Item.all.order('view DESC').first(3)
  end

  def new
    @item = Item.new
  end

  def create
  end

  private
#/ Cas où il a des carts mais aucune d'ouvert

  def cart_verification
    if  (signed_in?) && (current_user.carts.find_by("status = 0") == nil)
      @cart = Cart.new(user_id: current_user.id, status: 0)
      @cart.save
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def bootstrap_class_for_flash(type)
	  case type
	    when 'notice' then "alert-info"
	    when 'success' then "alert-success"
	    when 'error' then "alert-danger"
	    when 'alert' then "alert-warning"
	  end
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
	def item_in_cart?(id)
		result = false
		current_user.carts.each do |cart|
			cart.cart_items.each do |cart_item|
				if id == cart_item.item.id
					result = true
				end
			end
		end
		return result
	end
end

app/helpers/carts_helper.rb
module CartsHelper
	def cart_in_progress?
		current_user.carts.find_by("status = 0") != nil
	end

  def total_cart
    current_cart = current_user.carts.find_by("status = 0")

    subtotal=0
    current_cart.cart_items.each do |cart_item|
      price = cart_item.item.price * cart_item.quantity
      subtotal += price
    end
    return subtotal
  end

  def number_of_cart_items
    current_cart = current_user.carts.find_by("status = 0")
    return current_cart.cart_items.length
  end

  def current_cart
    current_cart = current_user.carts.find_by("status = 0")
    return current_cart
  end   

end

app/helpers/charges_helper.rb
module ChargesHelper
	 def shipping_fees
    current_cart = current_user.carts.find_by("status = 0")
    return current_cart.cart_items.length*2
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper

	def new_article?
	product_id = params[:id].to_i


		current_cart.cart_items.each do |cart_item|
			puts cart_item.item.id
					if cart_item.item.id == product_id
						puts false
						return false
					end
			 
		end
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper

	def current_user_profile?
    current_user.profile != nil
	end

  def order_amount(id)
    subtotal = 0
    id.cart_items.each do |cart_item|
      price = cart_item.item.price * cart_item.quantity
      subtotal += price
    end
    return subtotal
  end

end

app/views/admin/index.html.erb
    <section class="container pt-3 pb-4 mb-5" data-offset-top="110" id="services">
      <h2 class="h3 block-title text-center mb-3">Hello administrateur<small>Interface admin</small></h2>
      <div class="row">
        <div class="col-lg-4 col-sm-6">
          <div class="icon-box text-center mx-auto">
            <div class="icon-box-icon"><i class="far fa-images"></i></div>
            <h3 class="icon-box-title">Produits</h3>
              <%= link_to "Tous les produits", admin_items_path, class:"btn btn-secondary btn-sm mb-2" %>
              <%= link_to "Ajouter un produit", new_admin_item_path, class:"btn btn-secondary btn-sm" %>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
          <div class="icon-box text-center mx-auto">
            <div class="icon-box-icon"><i class="fas fa-users"></i></div>
            <h3 class="icon-box-title">Utilisateurs</h3>
              <%= link_to "Tous les utilisateurs", admin_users_path, class:"btn btn-secondary btn-sm mb-2" %>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
          <div class="icon-box text-center mx-auto">
            <div class="icon-box-icon"><i class="fas fa-shopping-basket"></i></div>
            <h3 class="icon-box-title">Commandes et paniers</h3>
              <%= link_to "Toutes les commandes", admin_carts_path, class:"btn btn-secondary btn-sm mb-2" %>
          </div>
        </div>
      </div>
      <hr class="mt-5">
    </section>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true"></span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark pt-5">
      <div class="container pt-3 text-center">

        <h6 class="text-white text-center pt-4">© Trois petits chats</h6>

        <div class="pt-4">
          <hr class="hr-light">
        </div>
        <div class="d-md-flex justify-content-between align-items-center py-4 text-center text-md-left">
          <div class="order-2"><a class="social-btn sb-style-6 sb-facebook sb-light-skin" href="#"><i class="socicon-facebook"></i></a><a class="social-btn sb-style-6 sb-twitter sb-light-skin" href="#"><i class="socicon-twitter"></i></a><a class="social-btn sb-style-6 sb-linkedin sb-light-skin" href="#"><i class="socicon-linkedin"></i></a><a class="social-btn sb-style-6 sb-youtube sb-light-skin" href="#"><i class="socicon-youtube"></i></a><a class="social-btn sb-style-6 sb-behance sb-light-skin" href="#"><i class="socicon-behance"></i></a></div>
          <p class="m-0 text-sm text-white order-1"><span class="opacity-60">© Tous droits réservés. Fait avec</span> <i class="far fa-heart"></i> <a href="http://thehackingproject.herokuapp.com/" class="d-inline-block nav-link text-white opacity-60 p-0" target="_blank"> par THP Studio </a></p>
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<header class="navbar-wrapper navbar-sticky">

    <div class="d-table-cell align-middle pr-md-3">
      <%= link_to (image_tag("logo.png", class: "menu_icon")), root_path, class:"navbar-brand mr-1" %>
    </div>

      <div class="d-table-cell w-100 align-middle pl-md-3">
        <div class="navbar justify-content-end justify-content-lg-between">
          <!-- Search-->
          <form class="search-box" method="get">
            <div class="easy-autocomplete" style="width: 915px;"><input type="text" id="site-search" placeholder="Type A or C to see suggestions" autocomplete="off"><div class="easy-autocomplete-container" id="eac-container-site-search"><ul></ul></div></div><span class="search-close"><i class="fas fa-times"></i></span>
          </form>
          <!-- Main Menu-->
          <ul class="navbar-nav d-lg-block">
            <!-- Home-->
            <li class="nav-item mega-dropdown-toggle active"><%= link_to "Trois Petits Chats", root_path, class:"nav-link" %>
              <div class="dropdown-menu mega-dropdown">
                <div class="d-flex">
                </div>
              </div>
            </li>

            <!-- Account-->
            <li class="nav-item dropdown-toggle"><a class="nav-link">Mon compte</a>
                <ul class="dropdown-menu">
                    <%if user_signed_in?%>
                      <li class="dropdown-item">  <%= link_to "Changer l'email / le mot de passe", edit_user_registration_path %> </li>
                    <%if current_user_profile?%>
                      <li class="dropdown-item">  <%= link_to "Mes commandes", profile_path(current_user.profile.id) %> </li> <% end %>
                      <li class="dropdown-item"> <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %> </li>

                     <% else %>
                      <li class="dropdown-item"> <%= link_to "Connexion", new_user_session_path, class:"dropdown-item" %></li>
                      <li class="dropdown-item"><%= link_to "Inscription", new_user_registration_path, class:"dropdown-item" %></li>

                     <% end %>
                 </ul>
            </li>

          </ul>

            <!-- Search and shopping-cart-->
          <div>
            <ul class="navbar-buttons d-inline-block align-middle mr-lg-2">
              <li><a href="#" data-toggle="search"><i class="fas fa-search"></i></a></li>
              <%if user_signed_in?  %>
                    <% if cart_in_progress? %>
                      <li><a href="#shopping-cart" data-toggle="offcanvas"><i class="fas fa-shopping-cart"></i></a><span class="badge badge-danger"><%= number_of_cart_items %></span></li>
                    <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <!-- Off-Canvas Shopping Cart-->
      <div class="offcanvas-container is-triggered offcanvas-container-reverse" id="shopping-cart"><span class="offcanvas-close"><i class="fas fa-times"></i></span>
        <div class="px-4">
          <h6>Votre panier</h6>
          <div class="widget widget-cart pt-2">


          <%if user_signed_in?  %>
            <% if cart_in_progress? %>
                <% current_user.carts.last.cart_items.each do |cart_item| %>
                  <div class="featured-product">
                    <div class="featured-product-thumb">
                      <% if cart_item.item.item_picture.attached? %>
                        <%= image_tag cart_item.item.item_picture, alt: 'item picture' %>
                      <% else %>
                        <img src="<%= cart_item.item.image_url %>" alt="Product">
                      <% end %>
                    </div>
                    <div class="featured-product-info">
                      <h5 class="featured-product-title"><%= link_to cart_item.item.title, item_path(cart_item.item.id) %></h5><span class="featured-product-price"><%= cart_item.item.price %> €</span>
                    </div>
                    <span class="remove-product">
                  <%= link_to cart_item_path(cart_item.id), method: "delete", :class => "text-decoration-none", data: { confirm: "Are you sure about deleting this item from your list ?"} do %>
                  <i class="fas fa-times"></i>
                  <% end %>
                  </span>
                  </div>
                <% end %>

                <hr class="mt-3 mb-3"><span class="text-sm text-muted">Total :&nbsp;</span><strong><%= total_cart %> €</strong>
                <%= link_to "Voir le panier", cart_path(current_user.carts.last.id), class:"btn btn-primary btn-block btn-sm mr-2" %>
            <% end %>
          <% end %>

    </div>
  </div>
</div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Trois petits chats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <!-- icônes -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://d1azc1qln24ryf.cloudfront.net/114779/Socicon/style-cf.css?9ukd8d">

  </head>


  <body>

    <%= render 'layouts/header' %>

    <%= render 'layouts/flash'%>


    <%= yield %>
    <%= render 'layouts/footer'%>

  </body>



</html>