config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root "items#index"
  resources :items
  resources :carts
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  resources :cart_items
  resources :charges, only: [:new, :create]
  
  namespace :admin do
  	resources :items
    resources :users
    resources :carts
  	root 'admin#index'
  end

end

app/models/item.rb
class Item < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
	has_many :card_items
  validates :image_url, :title, :description, :price, presence: { message: "Merci de remplir tous les champs obligatoires!" };
  validates :price, numericality: { greater_than: 0,  message: "Le prix doit être supérieur à 0" };
  validates :description, length: { minimum: 20, message: "La description doit faire au minimum 20 caractères" };
  has_one_attached :item_picture # active storage


 def to_param
    [id, title.parameterize, 'en solde sur notre boutique trois petits chats'.parameterize].join("-")
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < AdminController
  def index
    @items = Item.all.order(:id).reverse
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(title: params[:title],
                       description: params[:description],
                       price: params[:price],
                       author: params[:author],
                       view: params[:view],
                       dimension: params[:dimension],
                       image_url: params[:image_url]
                       )
    @item.item_picture.attach(params[:item_picture])

    if @item.save # essaie de sauvegarder en base @item
      redirect_to admin_item_path(@item.id), :success => "Item créé !"
    else
      render 'new'
    end
  end

  def update
    @item = Item.find(params[:id])
    item_params = params.permit(:title, :description, :price, :image_url, :author, :view, :dimension)

    if params[:item_picture] != nil
      @item.item_picture.attach(params[:item_picture])
    end

      if @item.update(item_params)
        redirect_to admin_item_path(@item.id), :notice => "Item mis à jour"
      else
        render :show
      end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
before_action :cart_verification, only: [:index]


  def index
    @items = Item.all.order(:id).reverse
  end

  def show
  @item = Item.find(params[:id].to_i)
  @item.increment!(:view)
  @best_items = Item.all.order('view DESC').first(3)
  end

  def new
    @item = Item.new
  end

  def create
  end

  private
#/ Cas où il a des carts mais aucune d'ouvert

  def cart_verification
    if  (signed_in?) && (current_user.carts.find_by("status = 0") == nil)
      @cart = Cart.new(user_id: current_user.id, status: 0)
      @cart.save
    end
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper

	def new_article?
	product_id = params[:id].to_i


		current_cart.cart_items.each do |cart_item|
			puts cart_item.item.id
					if cart_item.item.id == product_id
						puts false
						return false
					end
			 
		end
	end
end

app/views/items/_banner.html.erb
<!-- Background Image Parallax -->
<div class="bg-parallax py-5">
  <span class="bg-overlay" style="opacity: .3;"></span>
  <div class="bg-parallax-img" data-parallax='{"y" : -100}'>
    <%= image_tag("banner.jpg", class: "Parallax Background") %>
  </div>
  <div class="bg-parallax-content px-4 py-5 mx-auto mt-4 mb-2 text-center" style="max-width: 600px;">
    <h2 class="text-white"><i class="fas fa-camera-retro"></i> Trois petits chats</h2>
    <p class="text-white opacity-80 pb-5">Les meilleures photos de chatons !</p>
    <%= link_to "Je m'inscris !", new_user_registration_path, :class => "btn btn-gradient" %>
  </div>
</div>

app/views/items/_small_banner.html.erb
    <!-- Small banner -->
    <div id="small-banner" class="page-title d-flex" aria-label="Page title">
      <div class="container text-left align-self-center">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
            <li class="breadcrumb-item"><%= link_to "Shop", root_path %></li>
          </ol>
        </nav>
        <h1 class="page-title-heading">Photo numéro <%=params[:id].to_i%></h1>
      </div>
    </div>

app/views/items/index.html.erb
<%= render 'banner' %>

<div class="row mt-5 mx-md-3">

  <!-- Card -->
  <% @items.each do |item| %>
  <div class="col-sm-6 col-md-4 col-xs-12">
  <div class="card mb-30 mx-md-3 mx-xs-0">
    <% if item.item_picture.attached? %>
      <%= image_tag item.item_picture, alt: 'item picture' %>
    <% else %>
      <img src="<%= item.image_url %>" alt="Card image">
    <% end %>
    <div class="card-body">
      <h4 class="card-title"><%= item.title %></h4>
      <p class="card-text"> Description : <%= item.description %></p>
      <p class="card-text"> Prix : <%= item.price %> €</p>
    </div>
    <div class="card-footer text-muted text-sm">
        <%= link_to "Voir le produit", item_path(item), :class => "btn btn-style-6 btn-gradient" %>  
      
    </div>
  </div>
  </div>
  <% end %>

</div> <!-- fin row -->

app/views/items/new.html.erb
<div class="content row justify-content-md-center">
  <div class="card col-lg-6">
    <div class="card-body">
  <h1 class="mb-3">Ajouter un item</h1>

  <%= form_tag url_for(action: 'create'), method: "post", multipart: true do %>
        <div class="form-group">
          <%= label_tag 'Image :'%>
          <%= file_field_tag :item_picture  %>
          <%= text_field_tag 'title', @item.title, class: "form-control mb-1", placeholder: "Le titre" %>
          <%= text_area_tag 'description', @item.description, class: "form-control mb-1", placeholder: "Description" %>
          <%= text_field_tag 'price', @item.price, class: "form-control mb-1", placeholder: "Prix" %>
          <%= text_field_tag 'author', @item.author, class: "form-control mb-1", placeholder: "Auteur" %>
          <%= text_field_tag 'view', @item.view, class: "form-control mb-1", placeholder: "Vues" %>
          <%= text_field_tag 'dimension', @item.dimension, class: "form-control mb-1", placeholder: "Dimensions" %>
          <%= text_field_tag 'image_url', @item.dimension, class: "form-control mb-1", placeholder: "image_url" %>
          <br />
          <%= submit_tag "Ajouter mon item", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
</div>
    <% if @item.errors.any? %>
      <div class="alert alert-danger" role="alert">
          <p>Nous n'avons pas réussi à créer l'item' pour la (ou les) raison(s) suivante(s) :</p>
          <ul>
            <% @item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
      </div>
    <% end %>
</div>

app/views/items/show.html.erb
  <%= render 'small_banner' %>

  <!-- Product List View -->
  <div class= "container">
    <div class="card portfolio-card portfolio-list">
      <% if @item.item_picture.attached? %>
        <%= image_tag @item.item_picture, alt: 'item picture', id:'image_item' %>
      <% else %>
        <a class="portfolio-thumb" style="background-image: url(<%= @item.image_url %>);"></a>
      <% end %>
        <div id="description_item" class="card-body">
          <div class="portfolio-meta">
            <span class="mr-3"><i class="far fa-user"></i> <%= @item.author %></span>
            <span class="mr-3"><i class="far fa-heart"></i> 12 </span>
            <i class="far fa-bookmark"></i><a href="#"> Chaton</a>, <a href="#">mignon</a>
          </div>
          <h2 class="h3 font-weight-bold block-title"><%= @item.title %></h2>
          <h3 class="h4 font-weight-light"><%= @item.price %> €</h3>
          <p class="text-muted">Description : <%= @item.description %></p>

        <!-- Add to cart Button -->
          <div class="row align-items-end pb-4">
       
            <div class="col-sm-12">
              <div class="pt-4 hidden-sm-up"></div>
       
              <% if signed_in?  %>
                <% if new_article? %>
                  <%= button_to "Add to cart", cart_items_path(params[:id].to_i), method: :post, :class => "btn btn-primary btn-block m-0", "data-toggle" =>"modal", "data-target" => "#modalCentered", remote: true %>
                  <%else%>
                    <div class="alert alert-primary" role="alert">
                    Ce produit est déjà dans votre panier
                    </div>
                  <%end%>
              <% else %>
                <%= button_to "Se connecter pour acheter", new_user_session_path, method: :get, :class => "btn btn-primary btn-block m-0" %>
              <% end %>
            </div>
          </div> <!-- fin add-to-cart-button -->

          <!-- Center Aligned -->
          <div class="text-center">
            <h5 class="block-title">
              <%= rand(40..100) %>
              <small>utilisateurs en train de regarder cet article</small>
            </h5>
          </div>

        </div>
    </div>
<br>
<br>

<h4>Produits les plus consultés</h4>
<div class="row mt-5 mx-md-3">

  <!-- Card -->
  <% @best_items.each do |item| %>
  <div class="col-sm-6 col-md-4 col-xs-12">
  <div class="card mb-30 mx-md-3 mx-xs-0">
    <% if item.item_picture.attached? %>
      <%= image_tag item.item_picture, alt: 'item picture' %>
    <% else %>
      <img src="<%= item.image_url %>" alt="Card image">
    <% end %>
    <div class="card-body">
      <h4 class="card-title"><%= item.title %></h4>
      <p class="card-text"> Description : <%= item.description %></p>
      <p class="card-text"> Prix : <%= item.price %> €</p>
    </div>
    <div class="card-footer text-muted text-sm">
        <%= link_to "Voir le produit", item_path(item), :class => "btn btn-style-6 btn-gradient" %>  
      
    </div>
  </div>
  </div>
  <% end %>

</div> <!-- fin row -->



 </div> <!-- fin container -->


<!-- Social Networks Widget -->
<div class= "container">
  <div class="widget p-5">
    <h4 class="widget-title"> Réseaux Sociaux </h4>
    <a class="social-btn sb-style-6 sb-facebook" href="#" data-placement="top" title="Facebook">
      <i class="socicon-facebook"></i>
    </a>
    <a class="social-btn sb-style-6 sb-dribbble" href="#" data-placement="top" title="Dribbble">
      <i class="socicon-dribbble"></i>
    </a>
    <a class="social-btn sb-style-6 sb-twitter" href="#" data-placement="top" title="Twitter">
      <i class="socicon-twitter"></i>
    </a>
  </div>
</div>

<!-- Vertically Centered Modal -->
<% if signed_in?  %>
  <div class="modal fade" id="modalCentered" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Ajout d'un article</h4>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <p>Photo bien ajoutée au panier 😻</p>
        </div>
        <div class="modal-footer">

           <%= button_to "Voir mon panier", cart_path(current_user.carts.last), method: :get, :class => "btn btn-primary btn-sm"%>

          <%= button_to "Continuer mes achats", items_path, method: :get, :class => "btn btn-secondary btn-sm"%>

        </div>
      </div>
    </div>
  </div>
<% end %>