config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root "items#index"
  resources :items
  resources :carts
  resources :profiles, only: [:show, :new, :create, :edit, :update]
  resources :cart_items
  resources :charges, only: [:new, :create]
  
  namespace :admin do
  	resources :items
    resources :users
    resources :carts
  	root 'admin#index'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :welcome_send
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 	has_one :profile


 	has_many :carts

  def welcome_send
  	UserMailer.welcome_email(self).deliver_now
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

	def index
		@users = User.all.order(:id).reverse
	end

	def show
		@user = User.find(params[:id])
		@profile = @user.profile
		@orders = @user.carts.where("status=1")
	  @carts = @user.carts.where("status=0")
	end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_small_banner.html.erb
    <!-- Small banner -->
    <div id="small-banner" class="page-title d-flex" aria-label="Page title">
      <div class="container text-left align-self-center">
        <h1 class="page-title-heading">Admin User n°<%= @user.id%></h1>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to "Accueil Admin", admin_root_path %></li>
            <li class="breadcrumb-item"><%= link_to "Tous les utilisateurs", admin_users_path %></li>
          </ol>
        </nav>
      </div>
    </div>

app/views/admin/users/index.html.erb
<div class="container mt-5">
	<h3> <i class="far fa-id-card"></i> Récapitulatif Users </h3>
	<br><br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col"> Nom </th>
      <th scope="col"> Prénom </th>
      <th scope="col"> Email </th>
      <th scope="col">Détail commande</th>
    </tr>
  </thead>
  <tbody>
 <% @users.each do |user| %>
    <tr>
      <th scope="row"><%= user.id %></th>
      <td><%= user.profile.present? ? user.profile.last_name : "N#A" %> </td>
      <td><%= user.profile.present? ? user.profile.first_name : "N#A" %> </td>
      <td><%= user.email %> </td>
      <td><%=link_to 'Voir les commandes', admin_user_path(user.id), class:'btn btn-secondary' %></td>
    </tr>
<%end%>
  </tbody>
</table>
</div>

app/views/admin/users/show.html.erb
<%= render 'small_banner' %>

<div class="container mt-5 mb-5">
    <div class ="row">
        <div class="card col-12">
            <div class="card-body">
                <div class="author-card pb-3">
                    <div class="author-card-cover"></div>
                        <div class="author-card-profile mt-30" >
                            <div class="author-card-details">
                            <h5 class="author-card-name text-lg">
                            <h6><%= @user.profile.present? ? @profile.first_name  : "N#A" %> <%= @user.profile.present? ? @profile.last_name  : "N#A"  %></h6></h5>
                            <span class="author-card-position"><%= @user.created_at %></span>
                        </div>
                        <div class="widget widget-contacts">
                            <ul>
                                <li>
                                    <i class="fas fa-home"></i>                   
                                    <span> Adresse </span>
                                    <a><%=  @user.profile.present? ? @profile.street : "N#A" %>, <%= @user.profile.present? ? @profile.zip_code : "N#A" %>, <%= @user.profile.present? ? @profile.city : "N#A"  %></a>
                                </li>
                                <li>
                                    <i class="fas fa-at"></i>
                                    <span> Email </span>
                                    <a><%= @user.profile.present? ? @profile.user.email : "N#A" %></a>
                                </li>
                                <li>
                                    <i class="fas fa-phone"></i>
                                    <span> Téléphone </span>
                                    <a><%= @user.profile.present? ? @profile.phone_number : "N#A"  %></a>
                              </li>
                          </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 

<div class="container pt-5">
    <h3 class ="m-3"><i class="fas fa-shipping-fast"></i> Commandes passées </h3>
          <% if @orders[0] == nil %>
              <p class ="m-5"> Aucune commande passée </p>
          <% else %>
              <table class="table">
                  <thead>
                      <tr>
                          <th scope="col">Date</br><small class="font-italic">Paiement</small></th>
                          <th scope="col">Id</th>
                          <th scope="col">Statut</th>
                          <th scope="col">Montant du panier</th>
                          <th scope="col">Frais de livraison</th>
                          <th scope="col">Montant total</th>
                          <th scope="col">Voir détail</th>
                      </tr>
                  </thead>
                  <% @orders.each_with_index do |order, i| %>
                      <tbody>
                          <tr>
                            <td><%= order.updated_at %> </td>
                            <td><%= order.id %> </td>
                            <td><%= order.status %> </td>
                            <td><%= order_amount(order)%></td>
                            <td><%= number_of_items(order)*2 %> €</td>
                            <td><%= order_amount(order) + (number_of_items(order)*2) %></td>
                            <td><%=link_to 'Détail Commande', admin_cart_path(order.id), class:"btn btn-secondary"%></td>
                            </tr>
                      </tbody>
                  <% end %>
             </table>
         <% end %>
</div> 
        
<div class="container mb-5 pb-5">         
    <h3 class ="m-3"><i class="fas fa-shopping-basket"></i> Panier en cours </h3>
    <% if @carts[0] == nil %>
        <p class ="ml-5"> Pas de panier en cours </p>
    <% else %>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Date</br><small class="font-italic">Dernier changement</small></th>
                    <th scope="col">Id</th>
                    <th scope="col">Status</th>
                    <th scope="col">Montant du panier</th>
                    <th scope="col">Frais de livraison</th>
                    <th scope="col">Montant total</th>
                    <th scope="col">Voir détail</th>
                </tr>
            </thead>
            <% @carts.each_with_index do |cart, i| %>
                <tbody>
                    <tr>
                      <td><%= cart.updated_at %> </td>
                      <td><%= cart.id %> </td>
                      <td><span class="badge badge-info m-0"><%= cart.status %> </td>
                      <td><%= order_amount(cart)%></td>
                      <td><%= number_of_items(cart)*2 %> €</td>
                      <td><%= order_amount(cart) + (number_of_items(cart)*2) %></td>
                      <td><%=link_to 'Détail Panier', admin_cart_path(cart.id), class:"btn btn-secondary"%>
                      </tr>
                </tbody>
            <% end %>
       </table>
    <% end %>  
</div>